### ISSUE TITLE
Decoding the encoded message

### ISSUE THREAD

**Issue by kiddpt** [meinestadt/glue-schema-registry#333]
The documentation currently demonstrates how to decode a message using a defined schema by specifying the schema in the code when decoding a message from Kafka:

```
 const schema = avro.Type.forSchema({
        type: "record",
        name: "property",
        namespace: "de.meinestadt.demo",
        fields: [
            { name: "demo", type: "string", default: "Hello World" },
        ]
    });
    const dataset = await registry.decode(message.value, schema);
```

I believe it would be more convenient if the schema were fetched directly from the registry, similar to how it's handled in the @kafkajs/confluent-schema-registry. According to their documentation, you don't need to explicitly specify the schema; you can simply decode the message using the registry:

`// Decode the payload
const decodedPayload = await registry.decode(encodedPayload)`

This approach streamlines the process and reduces the need for manual schema specification in your code.

**Comment by felix-iw** [comment]
Usually an application is developed for a specific schema, and for that schema one usually has a type definition, interface, class etc. By specifying the target schema, the library has a chance to convert the message from the schema it was encoded with, into the data structure the application expects.
Skipping that step would require the application to be able to handle data of a not clearly defined type.
Javascript is quite flexible in that regard, and in Typescript you could use the any type.
But is that really useful? What would be the use case?

And last but not least, if you don't use schema evolution and just process the data structure as it comes in, what's the reason for using the schema registry then?

**Comment by kiddpt** [comment]
The use case would be: the application has to be able to cater for multiple schema of data that comes in to the consumer without the need to redeploy all consumer applications when non breaking change to the schema comes in. What happens when old and new producers with 2 different schemas write into the log, would the new application with a strict schema hard-coded into the system be able to smoothly process the little change in the schema? Some applications need to be deployed without ever halting the operations in real time resulting in delays to business critical analytics.

**Comment by felix-iw** [comment]
That's exactly what happens. Let's say you use version 1 of a schema in you consumer application. Now the producer updates the schema to version 2 which is backward compatible. 
The existing consumers, which still expect version one, would now receive version two messages and the library would take care of converting them back into version one. 
That means that the consumers don't need to change as long as the new version is compatible (non breaking change) to the old one. 

In your consumer application you specify the type you want/your application was built for, the library automatically reads the schema version of the incoming message, loads the schema from the schema registry when needed, and then converts it to the locally expected schema. 

Does that clarify how the lib is meant to work?

**Comment by felix-iw** [comment]
By the way, when you use the library also for your producer, you can introduce your non-breaking change there first. The library would recognize the schema change and register a new version at the glue schema registry automatically. With the right settings, Glue would also check if your compatibility requirements are met. 
The existing consumers would still be able to consume the messages by converting them back into the schema version they expect, see my post above. 

This is a "producer-first" approach, where you first update the schema in the producer, and later in the consumer. 
Of course you could also follow a "consumer-first" approach, depending on the needs of your application.

**Comment by felix-iw** [comment]
@kiddpt do my answers fill your needs, or do you still have a need for an adjusted interface?

**Comment by felix-iw** [comment]
I will close the issue as I haven't heard back.
Please reopen it if you still see a need for the feature or if you want to discuss it further.
