### ISSUE TITLE
Switch to async zlib methods

### ISSUE THREAD

**Issue by ethanresnick** [meinestadt/glue-schema-registry#56]
Hi again :)

One other thought I had: should this library use the async versions of zlib inflate/deflate, rather than the sync versions? It seems like sync versions would have some considerable risk of blocking Node's main thread, which could be a big footgun in the web server context. Meanwhile, the async versions look fairly straightforward to switch to.

**Comment by felix-iw** [comment]
Thank you very much for your input. I agree with you in general that the async version should be preferred.
I used the sync version as the buffer with the data is already fully loaded, and should be relatively small in most cases.

But I will consider changing the implementation, as I see no disadvantage using the async version.
Thank you again for your input!

**Comment by ethanresnick** [comment]
Sounds good!
